#! /bin/bash

startup=/vagrant/start-jenkins.sh
shutdown=/vagrant/stop-jenkins.sh
 
start(){
 su - jenkins -c $startup
}
 
stop(){
 su - jenkins -c $shutdown
}
 
status(){
 numproc=`ps -ef | grep [j]enkins.war | wc -l`
 if [ $numproc -gt 0 ]; then
  echo "Jenkins is running..."
  else
  echo "Jenkins is stopped..."
 fi
}
 
restart(){
  stop
  sleep 5
  start
}
 
 
# See how we were called.
case "$1" in
start)
 start
 ;;
stop)
 stop
 ;;
status)
 status
 ;;
restart)
 restart
 ;;
*)
 echo $"Usage: $0 {start|stop|status|restart}"
 exit 1
esac
 
exit 0
